sudo: false
language: node_js
node_js:
  - 12
git:
  depth: 3
cache: yarn
install:
  - make install
script:
  - jsinspect --ignore src/ExecLimit.js src
  - make test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
