sudo: false
language: node_js
node_js:
  - 12
git:
  depth: 3
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
install:
  - make install
script:
  - jsinspect --ignore src/ExecLimit.js src
  - make test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
